require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoffeeOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # CoffeeOrder. As you add validations to CoffeeOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoffeeOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coffee_orders as @coffee_orders" do
      coffee_order = CoffeeOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coffee_orders).should eq([coffee_order])
    end
  end

  describe "GET show" do
    it "assigns the requested coffee_order as @coffee_order" do
      coffee_order = CoffeeOrder.create! valid_attributes
      get :show, {:id => coffee_order.to_param}, valid_session
      assigns(:coffee_order).should eq(coffee_order)
    end
  end

  describe "GET new" do
    it "assigns a new coffee_order as @coffee_order" do
      get :new, {}, valid_session
      assigns(:coffee_order).should be_a_new(CoffeeOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested coffee_order as @coffee_order" do
      coffee_order = CoffeeOrder.create! valid_attributes
      get :edit, {:id => coffee_order.to_param}, valid_session
      assigns(:coffee_order).should eq(coffee_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoffeeOrder" do
        expect {
          post :create, {:coffee_order => valid_attributes}, valid_session
        }.to change(CoffeeOrder, :count).by(1)
      end

      it "assigns a newly created coffee_order as @coffee_order" do
        post :create, {:coffee_order => valid_attributes}, valid_session
        assigns(:coffee_order).should be_a(CoffeeOrder)
        assigns(:coffee_order).should be_persisted
      end

      it "redirects to the created coffee_order" do
        post :create, {:coffee_order => valid_attributes}, valid_session
        response.should redirect_to(CoffeeOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coffee_order as @coffee_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeOrder.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_order => {  }}, valid_session
        assigns(:coffee_order).should be_a_new(CoffeeOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeOrder.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_order => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coffee_order" do
        coffee_order = CoffeeOrder.create! valid_attributes
        # Assuming there are no other coffee_orders in the database, this
        # specifies that the CoffeeOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoffeeOrder.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => coffee_order.to_param, :coffee_order => { "these" => "params" }}, valid_session
      end

      it "assigns the requested coffee_order as @coffee_order" do
        coffee_order = CoffeeOrder.create! valid_attributes
        put :update, {:id => coffee_order.to_param, :coffee_order => valid_attributes}, valid_session
        assigns(:coffee_order).should eq(coffee_order)
      end

      it "redirects to the coffee_order" do
        coffee_order = CoffeeOrder.create! valid_attributes
        put :update, {:id => coffee_order.to_param, :coffee_order => valid_attributes}, valid_session
        response.should redirect_to(coffee_order)
      end
    end

    describe "with invalid params" do
      it "assigns the coffee_order as @coffee_order" do
        coffee_order = CoffeeOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_order.to_param, :coffee_order => {  }}, valid_session
        assigns(:coffee_order).should eq(coffee_order)
      end

      it "re-renders the 'edit' template" do
        coffee_order = CoffeeOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_order.to_param, :coffee_order => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coffee_order" do
      coffee_order = CoffeeOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => coffee_order.to_param}, valid_session
      }.to change(CoffeeOrder, :count).by(-1)
    end

    it "redirects to the coffee_orders list" do
      coffee_order = CoffeeOrder.create! valid_attributes
      delete :destroy, {:id => coffee_order.to_param}, valid_session
      response.should redirect_to(coffee_orders_url)
    end
  end

end
